### ISSUE TITLE
How to pass session id with SOAP request

### ISSUE THREAD

**Issue by vikramarka** [andrewmcgivery/angular-soap#15]
Hi,
I might be wrong with this one. But Magent api requires to send session id for each call. It's equivalant PHP code is this:

$proxy = new SoapClient('http://magentohost/api/soap/?wsdl');

$newCustomer = array(
    'firstname'  => 'First',
    'lastname'   => 'Last',
    'email'      => 'test@example.com',
    //for my version of magento (1.3.2.4) you SHOULD NOT
    // hash the password, as in:
    // 'password_hash' => 'password'
    'password_hash'   => md5('password'),
    // password hash can be either regular or salted md5:
    // $hash = md5($password);
    // $hash = md5($salt.$password).':'.$salt;
    // both variants are valid
    'store_id'   => 0,
    'website_id' => 0
);

$newCustomerId = $proxy->call($sessionId, 'customer.create', array($newCustomer));

As you can see, sessionId is being passed along with method and data. How can we do this with JS API, or am I wrong in thinking like this.

Right now login to API is working for me, from which I can retrieve session id but it is giving error when I call above method.

Any ideas?

**Comment by vikramarka** [comment]
Please..

**Comment by andrewmcgivery** [comment]
Does the $sessionId have to be sent along in a header?
