### ISSUE TITLE
Multiple items

### ISSUE THREAD

**Issue by Read1337** [andrewmcgivery/angular-soap#23]
When i make a call  i am only getting one item. I can see the XHR request and i can see that there are multiple items.

**Comment by digitalgarage** [comment]
Hi, sorry to hijack this thread.  I had the exact same issue.  Tracking back through the code I think it's to do with the way the version of soapclient.js bundled with angular-soap handles arrays.

There's a drop in replacement for soapclient.js here (https://github.com/gtathub/js-soap-client) that checking with diff seems to have a bit more array handling in the responses.  I just used gtahub's version of the soapclient.js with the angular-soap client and it picked up arrays perfectly.

@andrewmcgivery I don't know if you'd be able to merge in the changes from gtahub's version of soapclient.js or wanted a PR for this?

Eric.

**Comment by andrewmcgivery** [comment]
@digitalgarage I had no idea there was an updated fork. Thanks for letting me know!

If you could submit a PR for this and reference this issue, I would greatly appreciate that.

**Comment by ericfernance** [comment]
No probs.  I will raise a PR later today or worst case tomorrow.  I'm at work now.

EF.

**Comment by andrewmcgivery** [comment]
@digitalgarage When you do, can you submit it against the 3.0 branch? Thanks again!
