### ISSUE TITLE
how to set  header in soap.post

### ISSUE THREAD

**Issue by Overseas634** [andrewmcgivery/angular-soap#6]
Can you Please help me out how to set header while making soap.post cause im getting No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9000' is therefore not allowed access.
my code is 
angular.module('myAppApp')
  .controller('MainCtrl', function ($scope, $http, socket,soapService) {
   //   {console.log(data)})
  $scope.SOAPAction="http://radixx.com/WSRadixx/RadixxAdmin/EncryptLoginInfo";
  $scope.config={
      'Content-Type': 'text/xml;charset=utf-8',
      'Content-Length': 'length',
      'Access-Control-Allow-Origin': '*',
  }
 soapService.getData($scope.SOAPAction,$scope.config).then(function(response){
    console.log("soapService response",response)
    $scope.response = response;
  });
})

**Comment by andrewmcgivery** [comment]
Did you try Googling? ;)

Access-Control-Allow-Origin is a header that needs to be set on the server side, not the client side. It basically says allow everyone (*) to access me.

**Comment by Overseas634** [comment]
$scope.SOAPAction="http://radixx.com/WSRadixx/RadixxAdmin/EncryptLoginInfo";
  $scope.config={
      'Content-Type': 'text/xml;charset=utf-8',
      'Content-Length': 'length',
      'Access-Control-Allow-Origin': '*',
  }
 soapService.getData($scope.SOAPAction,$scope.config).then(function(response){
    console.log("soapService response",response)
    $scope.response = response;
  });
I have set header as above now im getting error like this can you help me out what is this..
i am not able to track whether this error coming due to header i hv set like this or response in not coming from other end

**Comment by rogeriotadim** [comment]
Hi @Overseas634 .

I'm trying consume RPC webservice that require Header's params to be set, too.

Did you solve that?

**Comment by arpit87** [comment]
Any way to add soap headers yet?

**Comment by Frecho12540** [comment]
Any solution? Hehehe

**Comment by MortezaFathnia** [comment]
Any solution?

**Comment by hugotown** [comment]
any solution ?
